[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev --no-interaction --ignore-platform-reqs"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
