[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.bcmath", "php82Extensions.zip", "php82Extensions.redis", "php82Extensions.sodium", "php82Extensions.opcache"]

[phases.install]
cmds = [
  "composer install --optimize-autoloader --no-dev --no-interaction --ignore-platform-reqs"
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
